
server:
  bind: "127.0.0.1"
  port: 3030
  allowed-origins: "*"
datastore:
  activity: testactivity.db
  config: config.db
settings:
  name: "appliance-monitor"
  monitorwindow: 120
  pushoverapikey: "ad2ujxv7zi7i5zw8fuvt5hu3chjuv4"